### ISSUE TITLE
error on update

### ISSUE THREAD

**Issue by cagnulein** [gzachos/cpu-temperature#1]
./log-cputemp.sh
ERROR: /var/www/html/cpu-temp/cputemp.rrd: illegal attempt to update using time 1546583668 when last update time is 1546583668 (minimum one second step)

**Comment by gzachos** [comment]
A Round Robin Database can be updated (at most) every 1 second (= step).
After adding this entry ```* * * * * /root/bin/log-cputemp.sh``` on the crontab file, the database ```cputemp.rrd``` will be updated every second. Now, if you try to run the script by hand while the cron job is running, you will correctly get this error. As you can see in the error message, you tried to update the database twice on 1546583668 (time in seconds since Epoch).

**Comment by cagnulein** [comment]
yes, you're right!
